name: 📌 일반 이슈
description: 버그, 제안, 질문 등 모든 종류의 이슈를 작성할 수 있습니다.
title: "[Issue] "
labels: []
body:
  - type: textarea
    attributes:
      label: 내용 설명
      description: 이슈에 대한 상세한 내용을 작성해주세요.
      placeholder: 어떤 문제가 발생했는지, 어떤 개선이 필요한지 등
  - type: input
    attributes:
      label: 환경 정보 (선택)
      placeholder: 예: Chrome 124 / macOS 14.4
  - type: textarea
    attributes:
      label: 참고 자료 (선택)
      description: 캡처, 로그, 관련 링크 등이 있다면 첨부해주세요.
